package synthesis

import (
	"fmt"
	"strings"
)

// BuildBriefing generates a markdown briefing from synthesis findings.
func BuildBriefing(date string, findings []Finding) string {
	if len(findings) == 0 {
		return fmt.Sprintf("# [Briefing] Weekly — %s\n\nQuiet week. Not enough activity to produce a meaningful briefing.\n\n---\nGenerated by Repository Strategist.", date)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# [Briefing] Weekly — %s\n\n", date)

	sections := map[string][]Finding{
		"cluster":         nil,
		"drift":           nil,
		"staleness":       nil,
		"upstream_signal": nil,
	}
	for _, f := range findings {
		sections[f.Type] = append(sections[f.Type], f)
	}

	if clusters := sections["cluster"]; len(clusters) > 0 {
		b.WriteString("## Emerging Patterns\n\n")
		for _, f := range clusters {
			writeFinding(&b, f)
		}
	}

	var drifts []Finding
	drifts = append(drifts, sections["drift"]...)
	drifts = append(drifts, sections["staleness"]...)
	if len(drifts) > 0 {
		b.WriteString("## Decision Health\n\n")
		for _, f := range drifts {
			writeFinding(&b, f)
		}
	}

	if upstream := sections["upstream_signal"]; len(upstream) > 0 {
		b.WriteString("## Upstream Signals\n\n")
		for _, f := range upstream {
			writeFinding(&b, f)
		}
	}

	b.WriteString("---\nGenerated by Repository Strategist. React with feedback or reply to discuss.\n")
	return b.String()
}

func writeFinding(b *strings.Builder, f Finding) {
	severity := ""
	if f.Severity == "action_needed" {
		severity = " [ACTION NEEDED]"
	}
	fmt.Fprintf(b, "**%s**%s\n\n", f.Title, severity)
	if f.Suggestion != "" {
		b.WriteString(f.Suggestion + "\n\n")
	}
	if len(f.Evidence) > 0 {
		b.WriteString("Evidence: " + strings.Join(f.Evidence, ", ") + "\n\n")
	}
}
